name: Syntax

on:
  push:
    branches:
      - main

jobs:
  syntax-check: 
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-python@v2
        with:
          python-version: '6.0.x'

      - name: Restire dependencies 
        run: dothet restore

      - name: Install NuGet package
        run: dothet add package E-Learning-Management-Web-App-master/E-Learning-Management-Web-App-master.csproj package Microsoft.CodeAnalysis.NetAnalyzers --version 8.0.0
      - name: Run Roslyn Analyzers
        run: dotnet build E-Learning-Management-Web-App-master/E-Learning-Management-Web-App-master.csproj /p:WarningLevel-6/p:DebugSymbols=false/ p:Platform="Any CPU"  /p:TreatWarningsAsErrors=true
     
